#------------------------------------------------------------------------------
#  Omar Amezquita 01/20/23 
#  Makefile for Lab1
#  make            makes Lab1
#  clean           removes binary files
#------------------------------------------------------------------------------
CC=gcc
make: 
	$(CC) src/myweb.c -o bin/myweb
clean:
	rm bin/output.dat bin/myweb


